_target_: src.datamodules.base.BaseDataModule

paths:
  train_data: "data/train.json"
  val_data:   "data/val.json"

prompt_template: |
  ### Инструкция:
  Раздели слово на морфемы и укажи тип каждой морфемы
  
  ### Слово:
  {word}
  
  ### Ответ:

tokenizer_kwargs:
  trunctation:        true
  max_length:         1024
  padding:            false
  add_special_tokens: true

dataloader_kwargs:
  batch_size:  4,
  shuffle:     true,
  pin_memory:  true,
  num_workers: 4

num_proc: 4