version: '3.8'

services:
  s3:
    image:   minio/minio
    restart: always
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_data:/data
    
  mlflow:
    image: ghcr.io/mlflow/mlflow
    restart: always
    environmet:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - MLFLOW_S3_ENDPOINT_URL=http://s3:9000
    command: >
      mlflow server
      --backend-store-uri sqlite://mlflow.db
      --default-artifact-root s3://mlflow/
      --host 0.0.0.0
    ports:
      - "5000:5000"