_target_: pytorch_lightning.Trainer

callbacks:
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: val_loss
    mode: min
    save_top_k: 2
    dirpath: ${run.dir}/checkpoints               
    filename: "{epoch:02d}-{val_loss:.4f}"
    save_last: true
    every_n_epochs: 1
    save_on_train_epoch_end: true               

  - _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: val_loss
    patience: 3
    mode: min

  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: step

  - _target_: pytorch_lightning.callbacks.RichProgressBar

max_epochs: 7
accelerator: gpu
devices: auto
enable_progress_bar: true

precision: bf16-mixed
accumulate_grad_batches: 4

limit_val_batches: 1.0
log_every_n_steps: 10
val_check_interval: 1.0
gradient_clip_val: 1.0