defaults:
  - _self_
  - input:  file_input
  - output: file_output

pipeline:
  _target_:        src.inference.pipeline.InferencePipeline
  prompt_template: ${datamodule.prompt_template}
  dataloader_kwargs:
    batch_size:  16
    num_workers: 4
    pin_memory:  true

predictor:
  _target_:        src.inference.predictor.Predictor
  model_cfg:       ${model}
  checkpoint_path: ${training.resume_from_checkpoint}