_target_: morphseg.datamodules.MorphologyDataModule

data_paths:
  train: data/train.jsonl
  val: data/val.jsonl

cache_dir: .cache/tokenized

prompt_template: |
  ### Инструкция:
  Вы — лингвист-эксперт, специализирующийся на морфемном и этимологическом анализе русского языка. 
  Ваша задача — проводить морфемный анализ слов, строго следуя принципам "Словообразовательный словарь русского языка" Тихонова А.Н.
  Ваша задача — выполнить морфемный анализ слова и определить его этимологический корень. 
  Морфемное членение слова ДОЛЖНО побуквенно совпадать с исходным словом и не должно изменять ни одной буквы.
  ### Слово: {word}
  ### Ответ: 

tokenizer_header_cfg:
  truncation: true
  max_length: 256
  padding: false
  add_special_tokens: false

tokenizer_target_cfg:
  truncation: true
  max_length: 128
  padding: false
  add_special_tokens: false

train_dataloader_cfg:
  batch_size: 8
  shuffle: true
  num_workers: 4
  pin_memory: true
  persistent_workers: true

val_dataloader_cfg:
  batch_size: 16
  shuffle: false
  num_workers: 4
  pin_memory: true
  persistent_workers: true

num_proc: 0

collator_cfg:
  _target_: morphseg.datamodules.DataCollatorContainingPrompt
  padding: "longest"
  label_pad_token_id: -100
  return_tensors: "pt"

logic_version: v2_version