defaults:
  - prompt_template: base_tikhonov
  - _self_

_target_: morphseg.datamodules.MorphologyDataModule

data_paths:
  train: data/soft-clean-oov/ru/tikhonov/train.jsonl
  val: data/soft-clean-oov/ru/tikhonov/val.jsonl

cache_dir: .cache/tokenized

tokenizer_prompt_cfg:
  truncation: true
  max_length: 800
  padding: false

tokenizer_full_text_cfg:
  truncation: true
  max_length: 900
  padding: false

train_dataloader_cfg:
  batch_size: 4
  shuffle: true
  num_workers: 11
  pin_memory: true
  persistent_workers: true

val_dataloader_cfg:
  batch_size: 4
  shuffle: false
  num_workers: 11
  pin_memory: true
  persistent_workers: true

val_collator_cfg:
  _target_: morphseg.datamodules.DataCollatorForValidation
  padding: "longest"
  label_pad_token_id: -100
  return_tensors: "pt"

train_collator_cfg:
  _target_: transformers.DataCollatorForSeq2Seq
  padding: "longest"
  label_pad_token_id: -100
  return_tensors: "pt"

logic_version: v6_version