defaults:
  - _self_
  - inference/dataset: morphology
  - inference/input: file
  - inference/output: file
  - inference/loader: mlflow
  - datamodule: morphology_json
  - model: morphseg_inference_module

pipeline:
  _target_: morphseg.inference.InferencePipeline
  
  input_strategy: ${inference.input}
  output_strategy: ${inference.output}
  dataset_factory: ${inference.dataset}
  
  prompt_template: ${datamodule.prompt_template}
  
  dataloader_kwargs:
    batch_size: 16
    num_workers: 4
    pin_memory: true

  tokenizer_kwargs:
    truncation: true
    padding: true
    return_tensors: pt

  predictor:
    _target_: morphseg.inference.Predictor
    _recursive_: false
    model_cfg: ${model}
    device_type: cuda
    generation_kwargs:
      max_new_tokens: 64
  
hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: .hydra

  sweep:
    dir: outputs/${hydra.job.name}/multirun/${now:%Y-%m-%d}
    subdir: ${hydra.job.num}