defaults:
  - inference
  - _self_
  - override inference/input:  smoke
  - override inference/loader: local
  - override model:            smoke_inference

pipeline:
  predictor:
    device_type: cpu