defaults: 
  - _self_
  - datamodule: morphology_json
  - model: morphseg_module
  - trainer: gpu_base
  - logger: csv

run:
  dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}/test

run_info_dir: None

hydra:
  run:
    dir: ${run.dir}
  output_subdir: .hydra

  sweep:
    dir: ${run.dir}
    subdir: ${hydra.job.num}