defaults: 
  - _self_
  - datamodule: morphology_json
  - model: morphseg_module
  - training: run_params
  - trainer: gpu_base
  - logger: mlflow

paths:
  output_dir: outputs/train/${now:%Y-%m-%d}/${now:%H-%M-%S} 

hydra:
  run:
    dir: ${paths.output_dir}
  output_subdir: .hydra

  sweep:
    dir: ${paths.output_dir}
    subdir: ${hydra.job.num}