defaults: 
  - _self_
  - datamodule: base
  - model:      morphseg_module
  - training:   default
  - trainer:    default
  - logger:     mlflow
  - callback:   default


project_name:    "llm-morphseg"
experiment_name: "run_${now:%Y-%m-%d_%H-%M-%S}"
run_name:        "initial_test"

hydra:
  run:
    dir: outputs/${experiment_name}
