defaults:
  - _self_
  - inference/dataset:  morphology
  - inference/input:    file
  - inference/output:   file
  - datamodule:         morphology_json
  - model:              morphseg_module

ckpt_path:              "last_best_ckpt.txt" 

pipeline:
  _target_:             morphseg.inference.InferencePipeline
  
  input_strategy:       ${inference.input}
  output_strategy:      ${inference.output}
  dataset_factory:      ${inference.dataset}
  
  prompt_template:      ${datamodule.prompt_template}
  
  dataloader_kwargs:
    batch_size:         16
    num_workers:        4
    pin_memory:         true

  predictor:
    _target_:           morphseg.inference.Predictor
    _recursive_:        false
    model_cfg:          ${model}
    checkpoint_path:    ${ckpt_path}