defaults: 
  - _self_
  - datamodule:  morphology_json
  - model:       morphseg_module
  - training:    run_params
  - trainer:     gpu_base
  - logger:      mlflow
  - callbacks:    train_hooks


project_name:    "morph-seg-v2"
experiment_name: "llama-tuning"
run_name:        "${model.cfg.model_name}_lr${model.optimizer.lr}_bs${datamodule.dataloader_kwargs.batch_size}"

hydra:
  run:
    dir:          outputs/${project_name}/${experiment_name}/${run_name}_${now:%H-%M-%S}

