defaults: 
  - _self_
  - datamodule:  morphology_json
  - model:       morphseg_module
  - training:    run_params
  - trainer:     gpu_base
  - logger:      mlflow
  - callbacks:   train_hooks


project_name:    morph-seg-v2
experiment_name: llama-tuning
run_name:        ${model.pretrained.model_name}

hydra:
  run:
    dir:          outputs/train/${project_name}/${experiment_name}/${run_name}_${now:%H-%M-%S}

